name: supreme_fitness
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  ionicons: ^0.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  firebase_core_platform_interface: 4.5.1
  get: ^4.6.5
  google_sign_in: ^5.0.2
  cloud_firestore: ^2.2.0
  font_awesome_flutter: '>= 4.7.0'
  uuid: ^3.0.6
  provider: ^5.0.0  
  path: ^1.8.0
  image_picker: ^0.8.4
  lottie: ^1.4.2
  hexcolor: ^2.0.7
  share_plus: ^6.3.0
  firebase_messaging: ^13.1.0
  flutter_local_notifications: 
  device_info_plus: ^8.0.0
  firebase_storage: any
  permission_handler: any
  full_screen_image_null_safe: ^2.0.0
  pedometer: ^3.0.0
  chewie: ^1.2.2
  collection: any
  google_mobile_ads: ^1.3.0
  velocity_x: ^3.6.0
  chat_gpt_sdk:
    git:
      url: https://github.com/iampawan/Flutter-ChatGPT.git
  http: ^0.13.5
  flutter_stripe: ^2.3.0
  path_provider: ^2.0.12
  open_file: ^3.2.1
  syncfusion_flutter_pdf:
  flutter_easyloading: ^3.0.5
  flutter_tawk: ^0.1.0
  percent_indicator: ^4.2.3
  fluttertoast: ^8.2.1
  otp_text_field: ^1.1.3
  google_fonts: ^4.0.0
  awesome_notifications: ^0.0.6
  connectivity_plus: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.12
  sensors_plus: ^1.2.1
  animated_text_kit: ^4.2.2
  flutter_facebook_auth: ^3.0.0
  ffi: ^2.0.1
  dialog_flowtter:
  app_settings: 
  #pinput: ^2.2.21
  #google_mobile_ads: 2.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  animated_text_kit: ^4.2.2
  open_file: ^3.2.1
  ffi: ^2.0.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/dumbbell.png"
  
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

  assets:
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/login.png
    - assets/images/register.png
    - assets/images/user.png
    - assets/images/challenge.png
    - assets/images/fitness.png
    - assets/images/fitnesss.png
    - assets/images/img1.png
    - assets/images/bmi.png
    - assets/images/feedback.png
    - assets/images/play-button.png
    - assets/images/healthy-food.png
    - assets/images/exercise.png
    - assets/images/chatbot.png
    - assets/images/comments.png
    - assets/images/healthy-eating.png
    - assets/images/videos.png
    - assets/images/exercisebanner.png
    - assets/images/healthyfoodbanner.png
    - assets/images/food.png
    - assets/images/eatwell.png
    - assets/images/workout.png
    - assets/images/workout1.png
    - assets/images/workout2.png
    - assets/images/enter.png
    - assets/images/password.png
    - assets/images/contract.png
    - assets/images/food1.png
    - assets/images/report.png
    - assets/images/menu.png
    - assets/images/chatbot1.png
    - assets/images/exercise1.png
    - assets/images/comments1.png
    - assets/images/calculate.png
    - assets/images/circled-play.png
    - assets/images/counter.png
    - assets/images/calories.png
    - assets/images/bot.png
    - assets/images/diet.png
    - assets/icon/dumbbell.png
    - assets/icon/menu_icon.png
    - assets/icon/search.png
    - assets/images/DashboardImages/
    - assets/images/Category/
    - assets/calories.png
    - assets/locations.png
    - assets/stopwatch.png
    - assets/Splash.png
    - assets/
    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
